# Generated by Django 4.1.4 on 2022-12-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True, blank=False)),
                ('email', models.CharField(max_length=100, unique=True, blank=False)),
                ('password', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='', blank = True)),
                ('residence', models.CharField(max_length=100, blank = True)),
                ('DOB', models.DateField(default = '', blank = True)),
                ('about', models.TextField(max_length=500, blank = True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobId', models.UUIDField(primary_key=True, serialize=False)),
                ('jobTitle', models.CharField(max_length=50)),
                ('responsibility', models.TextField(max_length=500)),
                ('qualification', models.TextField(max_length=500)),
                ('preferredQualification', models.TextField(max_length=500)),
                ('jobCategory', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=20)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
            ],
        ),
    ]
