# Generated by Django 4.1.4 on 2023-01-29 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='role',
            field=models.CharField(default='freelance', max_length=100),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.date(2023, 1, 29)),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 1, 29)),
        ),
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 1, 29)),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='timestamp',
            field=models.DateField(default=datetime.date(2023, 1, 29)),
        ),
    ]
