# Generated by Django 4.1.4 on 2023-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='resume',
            field=models.FileField(blank=True, upload_to='./static/resumes'),
        ),
    ]
