# Generated by Django 4.1.4 on 2022-12-17 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('recommender', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobId',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
