# Generated by Django 4.1.4 on 2022-12-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateField(blank=True, default='2022-01-01'),
        ),
    ]
