# Generated by Django 4.1.4 on 2023-01-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_customeuser_role_alter_customeuser_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
