# Generated by Django 4.1.4 on 2023-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_alter_customeuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='title',
        ),
        migrations.AddField(
            model_name='customeuser',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
