# Generated by Django 4.1.4 on 2023-02-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_alter_customeuser_timestamp_alter_job_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='userId',
            new_name='user',
        ),
    ]
